# Generated by Django 2.2.6 on 2019-10-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_basicgeneric_user_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basicgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.BasicGeneric')),
                ('detail', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
            bases=('common.basicgeneric',),
        ),
    ]
